name: inv_aligner
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  adaptive_theme: ^3.1.1
  auto_route: ^5.0.2
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.2
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  easy_localization: ^3.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_bloc_patterns: ^0.11.0
  flutter_gen: ^5.1.0+1
  flutter_gen_runner: any
  flutter_svg: ^1.1.6
  fluttertoast: ^8.1.1
  freezed: ^2.2.0
  freezed_annotation: ^2.2.0
  image_picker: ^0.8.6
  json_serializable: ^6.5.3
  json_annotation: ^4.8.0
  logger: ^1.1.0
  responsive_sizer: ^3.1.1
  shared_preferences: ^2.0.15
  shimmer_pro: ^0.0.6
  animated_bottom_navigation_bar: ^1.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true
    
flutter:
  uses-material-design: true

  assets:
  - assets/
  - assets/imgs/
  - assets/svg/
  - assets/lang/
  - assets/fonts/

  fonts:
    - family: DIN
      fonts:
        - asset: assets/fonts/DIN-RegularAlternate.ttf
        - asset: assets/fonts/DIN-Bold.ttf
        - asset: assets/fonts/DIN-Light.ttf
        - asset: assets/fonts/DIN-Regular.ttf
        - asset: assets/fonts/DIN-Medium.ttf
        - asset: assets/fonts/DIN-BlackAlternate.ttf